name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
# TODO(firsching): change this back to the lean-toolchain after bumping to v4.20.0
rev = "188e831aec3c09baf3951a4ce92ac795a4cb13f9"

[[lean_exe]]
name = "overwrite_index"
srcDir = "scripts"
root = "overwrite_index"
exeName = "overwrite_index"
supportInterpreter = true
